name: Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  RUN_E2E_TESTS: false

jobs:
  tests:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python: [ '3.10', '3.11', '3.12' ]
        node: [ '18.x' ]

    name: Python ^${{ matrix.python }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python }}

    - name: Install dependencies
      run: make install

    - name: Build resources
      run: make build

    - name: Lint
      run: make lint

    - name: Run unit tests
      run: make test:unit

    - name: Run integration tests
      run: make test:integration

    # After a succefull deployment e2e tests can be run

    # - name: Run e2e tests
    #   run: make test:e2e

    # - uses: actions/upload-artifact@v4
    #   if: ${{ !cancelled() }}
    #   with:
    #     name: playwright-traces
    #     path: test-results/
